### ISSUE TITLE
프리셋을 위한 Style.css, Index.html 업데이트 하였습니다

### ISSUE THREAD

**Issue by codevilot** [ConnecTo-FrontEnd/Stopwatch#1]

**Comment by codevilot** [comment]
먼저 제가, html을 이용하여 간단한 프레임을 짜둘까요?

**Comment by chaerin-dev** [comment]
넵!!

**Comment by codevilot** [comment]
Init setting 다되면 말해주세요 그때부터 바로 fork하고 진행하겠습니다

**Comment by chaerin-dev** [comment]
넵!

**Comment by chaerin-dev** [comment]
@codevilot 제가 제 feature 브랜치에서 기능 개발을 완료하면 거기서 add, commit 이후에 push를 해당 feature 브랜치로 하고 -> feature finish -> feature publish를 하는 것이.. 맞나요..?

**Comment by codevilot** [comment]
맞습니다. 다하면 말씀해주시와요

**Comment by chaerin-dev** [comment]
@codevilot CONVENTION 추가해서 develop 브랜치에 업데이트 했습니다 이제 이어서 작업 시작하면 될 것 같습니다!
